# Name of the project
PROJECT_NAME = TELECOM_BILLING_SYSTEM

#Doxyfile folder
DOC = documentation

#All source code files
SRC = telecom.c\
src/telecom_operations.c

#All test source files
TEST_SRC = src/telecom_operations.c\
test/test_telecom_operations.c\
unity/unity.c

TEST_OUTPUT = Test_a.out

#All include folders with header files
INC = -Iinc\
-Iunity\

#Project Output Name
PROJECT_OUTPUT = telecom.out

#Document files
DOCUMENTATION_OUTPUT = documentation/html
Build :	
	gcc function1.c test_telecom.c unity/unity.c -Iunity
Run:
	./a.out